title: Java Version Manager for Windows
description: A lightweight, high-performance, color-coded Windows command-line utility designed to dynamically discover, download, and switch Java Development Kits (JDKs) and the entire JVM Ecosystem with native SDKMAN! parity.
logo: /assets/icon.png
image: /assets/icon.png
author:
  name: Alexéy Shishkin
  url: https://github.com/TheHawk09
theme: jekyll-theme-cayman
repository: DiamTek/Java-Version-Manager-Windows

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

include:
  - LICENSE
  - robots.txt
  - llms.txt
  - docs/CONTRIBUTING.md
  - docs/CODE_OF_CONDUCT.md
  - packages/choco/README.md
  - packages/msi/README.md

kramdown:
  input: GFM
  parse_block_html: true